version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: meu-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackazilian
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql